### ISSUE TITLE
migration for a existent Server

### ISSUE THREAD

**Issue by tuvok81** [TianYu-00/PalworldServerManager#4]
Hello, i will migrate my existent Server to your Manager..
i have install a fresh server and copy my Server Things in the folders.. 
but when i start the tool i see only the default PalworldSettings.ini the Server name is the default Server name from your tool and the settings are also not correct.. 

What can i do to import this and can see the settings for my server?

**Comment by tianyu-00** [comment]
Hello,
Currently, there isn't an import option for the PalworldSettings.ini file because Palworld Server Manager (PSM) doesn't directly read settings from it. Instead, it retrieves settings from a JSON file called ServerSettingsPreset.json. This file stores all the PSM settings data, including your server settings. As a result, you'll need to recreate your PalworldSettings.ini through PSM rather than simply copying and pasting it.
